apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: "unityserver"
spec:
  ports:
  - name: default
    portPolicy: Dynamic
    containerPort: 7776
  template:
    spec:
      containers:
      - name: unityserver
        image: docker.io/sihtinen/unityserver:latest
      resources:
        requests:
          memory: "2048Mi"
          cpu: "128m"
        limits:
          memory: "2048Mi"
          cpu: "128m"
